# https://embarkstudios.github.io/cargo-deny/

targets = [
    { triple = "aarch64-apple-darwin" },
    { triple = "aarch64-linux-android" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
]

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
ignore = []

[bans]
multiple-versions = "deny"
wildcards = "allow"        # at least until https://github.com/EmbarkStudios/cargo-deny/issues/241 is fixed
deny = []

skip = [
    { name = "base64" },              # gltf uses an old version
    { name = "cfg-if" },              # winit depends on an old version
    { name = "core-foundation" },     # winit depends on an old version
    { name = "core-foundation-sys" }, # winit depends on an old version
    { name = "core-graphics" },       # winit depends on an old version
    { name = "miniz_oxide" },         # image crate depends on an old version
]
skip-tree = []


[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.92 # We want really high confidence when inferring licenses from text
copyleft = "deny"
allow = [
    # "Apache-2.0 WITH LLVM-exception", # https://spdx.org/licenses/LLVM-exception.html
    "Apache-2.0",   # https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
    "BSD-2-Clause", # https://tldrlegal.com/license/bsd-2-clause-license-(freebsd)
    "BSD-3-Clause", # https://tldrlegal.com/license/bsd-3-clause-license-(revised)
    "BSL-1.0",      # https://tldrlegal.com/license/boost-software-license-1.0-explained
    "CC0-1.0",      # https://creativecommons.org/publicdomain/zero/1.0/
    "ISC",          # https://tldrlegal.com/license/-isc-license
    "MIT",          # https://tldrlegal.com/license/mit-license
    # "MPL-2.0",      # https://www.mozilla.org/en-US/MPL/2.0/FAQ/ - see Q11
    # "OpenSSL",      # https://www.openssl.org/source/license.html
    "Zlib", # https://tldrlegal.com/license/zlib-libpng-license-(zlib)
]
