#!/bin/sh

source ~/.emsdk/emsdk_env.sh
export EMMAKEN_CFLAGS="-o index.html -s USE_WEBGL2=1 -s USE_SDL=2 --preload-file examples/assets"
cargo build --example texture --target asmjs-unknown-emscripten
