[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2021"

[dependencies]
three-d = { path = "../../", default-features = false, features=["glutin-window"] }