#!/bin/sh

# ./build.sh
if [ -z "$RELEASE"  ]; then
  # --------------------------------------------------
  # DEVELOPMENT BUILD
  # --------------------------------------------------

  echo "Development build"

  RUST_BACKTRACE=1 cargo +nightly build --target wasm32-unknown-unknown --release
  wasm-bindgen ./target/wasm32-unknown-unknown/release/web.wasm --out-dir ./www/ --no-typescript --no-modules

# RELEASE=1 ./build.sh
else

  # --------------------------------------------------
  # RELEASE BUILD
  # --------------------------------------------------

  echo "Release build"

  cargo +nightly build --target wasm32-unknown-unknown --release &&
  wasm-bindgen ./target/wasm32-unknown-unknown/release/web.wasm --out-dir ./www/ --no-typescript --no-modules
fi